In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('student_pass_data.csv')

In [3]:
data.head()

,hours_studied,attendance,passed
0,1,40,0
1,2,55,0
2,2,80,0
3,3,50,0
4,3,65,0


In [4]:
data.isna().sum()

hours_studied    0
attendance       0
passed           0
dtype: int64

In [5]:
X = np.array(data[['hours_studied' ,'attendance']])
Y =np.array(data['passed']).reshape(24,1)

In [6]:
print(f"X(Shape) : {X.shape} , Y(Shape) : {Y.shape}  ")

X(Shape) : (24, 2) , Y(Shape) : (24, 1)  


In [7]:
rng = np.random.default_rng()
n = X.shape[0]

idx = np.arange(n)
rng.shuffle(idx)



In [8]:
idx

array([ 2, 11, 23, 20, 16, 18,  7,  4,  0, 13,  1,  9, 12, 10,  8, 19, 22,
        5, 17, 21, 15,  3,  6, 14])

In [9]:
split  = int(0.8 * n)
train_idx = idx[:split]
test_idx = idx[split:]


In [10]:
X_train,X_test = X[train_idx],X[test_idx]
Y_train,Y_test = Y[train_idx],Y[test_idx]

In [11]:
print(f"X_train(Shape) : {X_train.shape} , Y_train(Shape) : {Y_train.shape} , Y_test(Shape) : {Y_test.shape} , X_test(Shape) : {X_test.shape}")

X_train(Shape) : (19, 2) , Y_train(Shape) : (19, 1) , Y_test(Shape) : (5, 1) , X_test(Shape) : (5, 2)


In [12]:
def zscore(X_train):
    Z_mean = np.mean(X_train , axis= 0)
    Z_sigma = np.std(X_train ,axis= 0)
    # z = (X - Z_mean)/Z_sigma
    return  Z_mean,Z_sigma
def apply_scaler(X,mean,sigma):

    return (X- mean) / sigma

In [13]:
mean,std = zscore(X_train)

X_norm  =apply_scaler(X_train, mean,std)
X_test_norm  =apply_scaler(X_test,mean,std)

In [14]:
print(f"Actual X_train : {X_train} , Normalization X_train : {X_norm}")

Actual X_train : [[ 2 80]
 [ 7 90]
 [ 9 60]
 [ 4 85]
 [10 92]
 [ 2 45]
 [ 5 70]
 [ 3 65]
 [ 1 40]
 [ 8 95]
 [ 2 55]
 [ 6 62]
 [ 7 68]
 [ 6 78]
 [ 5 85]
 [ 3 78]
 [ 6 50]
 [ 4 60]
 [ 1 90]] , Normalization X_train : [[-1.06988867  0.55732057]
 [ 0.84783631  1.17296539]
 [ 1.6149263  -0.67396906]
 [-0.30279868  0.86514298]
 [ 1.9984713   1.29609435]
 [-1.06988867 -1.59743629]
 [ 0.08074632 -0.05832425]
 [-0.68634368 -0.36614665]
 [-1.45343367 -1.9052587 ]
 [ 1.23138131  1.4807878 ]
 [-1.06988867 -0.98179147]
 [ 0.46429131 -0.5508401 ]
 [ 0.84783631 -0.18145321]
 [ 0.46429131  0.43419161]
 [ 0.08074632  0.86514298]
 [-0.68634368  0.43419161]
 [ 0.46429131 -1.28961388]
 [-0.30279868 -0.67396906]
 [-1.45343367  1.17296539]]


In [15]:
def Relu(X):
    relu = np.maximum(0,X)
    # print(relu)

    return relu

In [16]:
tmp_activation = Relu(X_norm)

In [17]:
def sigmoid(X):
    err = 1 + np.exp(-X)
    z = 1 / err

    return z

In [18]:
tmp_array = np.array([-2,0,3])
tmp_activation_relu = Relu(tmp_array)
tmp_activation_sigmoid = sigmoid(tmp_array)
print(tmp_activation_sigmoid)
print(tmp_activation_relu)


[0.11920292 0.5        0.95257413]
[0 0 3]


In [21]:
def weights_bias(n_input,n_hidden,n_output):
    rng = np.random.default_rng()
    W1 = rng.standard_normal((n_input,n_hidden)) * 0.1
    B1 = np.zeros((1,n_hidden))
    W2 = rng.standard_normal((n_hidden,n_output)) * 0.1
    B2 = np.zeros((1,n_output))
    print(W1.shape)
    return W1,B1,W2,B2


In [22]:
W1,B1,W2,B2 = weights_bias(2,4,1)
print(W1.shape,B1.shape,W2.shape,B2.shape)

(2, 4)
(2, 4) (1, 4) (4, 1) (1, 1)
