In [113]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [114]:
data = pd.read_csv('student_pass_data.csv')

In [115]:
data.head()

,hours_studied,attendance,passed
0,1,40,0
1,2,55,0
2,2,80,0
3,3,50,0
4,3,65,0


In [116]:
data.isna().sum()

hours_studied    0
attendance       0
passed           0
dtype: int64

In [117]:
X = np.array(data[['hours_studied' ,'attendance']])
Y =np.array(data['passed']).reshape(24,1)

In [118]:
print(f"X(Shape) : {X.shape} , Y(Shape) : {Y.shape}  ")

X(Shape) : (24, 2) , Y(Shape) : (24, 1)  


In [119]:
rng = np.random.default_rng()
n = X.shape[0]

idx = np.arange(n)
rng.shuffle(idx)



In [120]:
idx

array([15, 20, 14, 10, 22, 23,  2,  7, 18, 21, 13,  9, 12,  6, 19,  8, 11,
        1, 16,  0,  3,  5, 17,  4])

In [121]:
split  = int(0.8 * n)
train_idx = idx[:split]
test_idx = idx[split:]


In [122]:
X_train,X_test = X[train_idx],X[test_idx]
Y_train,Y_test = Y[train_idx],Y[test_idx]

In [123]:
print(f"X_train(Shape) : {X_train.shape} , Y_train(Shape) : {Y_train.shape} , Y_test(Shape) : {Y_test.shape} , X_test(Shape) : {X_test.shape}")

X_train(Shape) : (19, 2) , Y_train(Shape) : (19, 1) , Y_test(Shape) : (5, 1) , X_test(Shape) : (5, 2)


In [124]:
def zscore(X_train):
    Z_mean = np.mean(X_train , axis= 0)
    Z_sigma = np.std(X_train ,axis= 0)
    # z = (X - Z_mean)/Z_sigma
    return  Z_mean,Z_sigma
def apply_scaler(X,mean,sigma):

    return (X- mean) / sigma

In [125]:
mean,std = zscore(X_train)

X_norm  =apply_scaler(X_train, mean,std)
X_test_norm  =apply_scaler(X_test,mean,std)

In [126]:
print(f"Actual X_train : {X_train} , Normalization X_train : {X_norm}")

Actual X_train : [[ 9 88]
 [ 4 85]
 [ 8 74]
 [ 6 78]
 [ 6 50]
 [ 9 60]
 [ 2 80]
 [ 5 70]
 [ 2 45]
 [ 5 55]
 [ 8 95]
 [ 6 62]
 [ 7 68]
 [ 4 72]
 [ 3 78]
 [ 5 85]
 [ 7 90]
 [ 2 55]
 [10 92]] , Normalization X_train : [[ 1.37739883  1.04779891]
 [-0.69963115  0.84185223]
 [ 0.96199283  0.08671439]
 [ 0.13118084  0.36130997]
 [ 0.13118084 -1.56085907]
 [ 1.37739883 -0.87437013]
 [-1.53044314  0.49860776]
 [-0.28422516 -0.18788118]
 [-1.53044314 -1.90410354]
 [-0.28422516 -1.2176146 ]
 [ 0.96199283  1.52834117]
 [ 0.13118084 -0.73707234]
 [ 0.54658684 -0.32517897]
 [-0.69963115 -0.0505834 ]
 [-1.11503715  0.36130997]
 [-0.28422516  0.84185223]
 [ 0.54658684  1.1850967 ]
 [-1.53044314 -1.2176146 ]
 [ 1.79280482  1.32239449]]


In [127]:
def Relu(X):
    relu = np.maximum(0,X)
    # print(relu)

    return relu

In [128]:
tmp_activation = Relu(X_norm)

In [129]:
def sigmoid(X):
    err = 1 + np.exp(-X)
    z = 1 / err

    return z

In [130]:
tmp_array = np.array([-2,0,3])
tmp_activation_relu = Relu(tmp_array)
tmp_activation_sigmoid = sigmoid(tmp_array)
print(tmp_activation_sigmoid)
print(tmp_activation_relu)


[0.11920292 0.5        0.95257413]
[0 0 3]


In [131]:
def weights_bias(n_input,n_hidden,n_output):
    rng = np.random.default_rng()
    W1 = rng.standard_normal((n_input,n_hidden)) * 0.1
    B1 = np.zeros((1,n_hidden))
    W2 = rng.standard_normal((n_hidden,n_output)) * 0.1
    B2 = np.zeros((1,n_output))
    print(W1.shape)
    return W1,B1,W2,B2


In [132]:
W1,B1,W2,B2 = weights_bias(2,4,1)
print(W1.shape,B1.shape,W2.shape,B2.shape)

(2, 4)
(2, 4) (1, 4) (4, 1) (1, 1)


In [133]:
def forward_pass(X,W1,B1,W2,B2):
    err_relu = np.dot(X,W1) + B1
    hidden_layer = Relu(err_relu)
    err_sigmoid = np.dot(hidden_layer,W2) + B2
    output_layer = sigmoid(err_sigmoid)

    return hidden_layer,output_layer

In [134]:
tmp_hidden,tmp_output = forward_pass(X_norm,W1,B1,W2,B2)
print(tmp_hidden.tolist())
print(tmp_output.tolist())


[[0.0, 0.0, 0.02635510455189694, 0.0], [0.0, 0.04305713989131349, 0.02175500821248432, 0.0], [0.007037521112529161, 0.0, 0.0019087991897775536, 0.0], [0.0, 0.0, 0.009198364212970092, 0.0], [0.027863460191748887, 0.021001615609959855, 0.0, 0.10614562262053621], [0.027158227332647642, 0.0, 0.0, 0.0], [0.0, 0.12201752893515005, 0.013243336306711801, 0.08888905952848786], [0.0006965211040007896, 0.02847282370298149, 0.0, 0.03752650816690026], [0.01901733613217608, 0.17180928560232261, 0.0, 0.2689429858342347], [0.018312103273074837, 0.0498121479889126, 0.0, 0.11469247658364892], [0.0, 0.0, 0.03877835202402936, 0.0], [0.013770994456489653, 0.003930156181214974, 0.0, 0.044412847887137306], [0.010404257784509407, 0.0, 0.0, 0.0], [0.0, 0.061551220939120445, 0.0, 0.06150655581336267], [0.0, 0.0889391316990111, 0.00959855379511553, 0.06490901188202544], [0.0, 0.007133499417050385, 0.02162161168510251, 0.0], [0.0, 0.0, 0.030133283590875023, 0.0], [0.007273614686126719, 0.1575830694117019, 0.0, 0.

In [135]:
print(tmp_hidden.shape)
print(tmp_output.shape)

(19, 4)
(19, 1)


In [142]:
def binary_cross_entropy(y_true,y_pred):
    eps = 1e-8
    y_pred = np.clip(y_pred,eps,1-eps)
    loss = -((y_true*np.log(y_pred)) + (1-y_true) * np.log(1 - y_pred))
    return np.mean(loss)

In [143]:
print(Y_train.shape)
print(tmp_output.shape)

(19, 1)
(19, 1)


In [144]:
loss = binary_cross_entropy(Y_train,tmp_output)
print(loss)

0.6942785881051039
