In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('student_pass_data.csv')

In [3]:
data.head()

,hours_studied,attendance,passed
0,1,40,0
1,2,55,0
2,2,80,0
3,3,50,0
4,3,65,0


In [4]:
data.isna().sum()

hours_studied    0
attendance       0
passed           0
dtype: int64

In [5]:
X = np.array(data[['hours_studied' ,'attendance']])
Y =np.array(data['passed']).reshape(24,1)

In [6]:
print(f"X(Shape) : {X.shape} , Y(Shape) : {Y.shape}  ")

X(Shape) : (24, 2) , Y(Shape) : (24, 1)  


In [7]:
rng = np.random.default_rng()
n = X.shape[0]

idx = np.arange(n)
rng.shuffle(idx)



In [8]:
idx

array([22,  6, 16, 13, 18, 21, 10, 15,  4,  9, 11, 14, 20,  7,  8,  1, 23,
        2, 19,  3, 17,  5,  0, 12])

In [9]:
split  = int(0.8 * n)
train_idx = idx[:split]
test_idx = idx[split:]


In [10]:
X_train,X_test = X[train_idx],X[test_idx]
Y_train,Y_test = Y[train_idx],Y[test_idx]

In [11]:
print(f"X_train(Shape) : {X_train.shape} , Y_train(Shape) : {Y_train.shape} , Y_test(Shape) : {Y_test.shape} , X_test(Shape) : {X_test.shape}")

X_train(Shape) : (19, 2) , Y_train(Shape) : (19, 1) , Y_test(Shape) : (5, 1) , X_test(Shape) : (5, 2)


In [12]:
def zscore(X_train):
    Z_mean = np.mean(X_train , axis= 0)
    Z_sigma = np.std(X_train ,axis= 0)
    # z = (X - Z_mean)/Z_sigma
    return  Z_mean,Z_sigma
def apply_scaler(X,mean,sigma):

    return (X- mean) / sigma

In [13]:
mean,std = zscore(X_train)

X_norm  =apply_scaler(X_train, mean,std)
X_test_norm  =apply_scaler(X_test,mean,std)

In [14]:
print(f"Actual X_train : {X_train} , Normalization X_train : {X_norm}")

Actual X_train : [[ 6 50]
 [ 4 72]
 [10 92]
 [ 8 95]
 [ 2 45]
 [ 5 55]
 [ 6 78]
 [ 9 88]
 [ 3 65]
 [ 6 62]
 [ 7 90]
 [ 8 74]
 [ 4 85]
 [ 5 70]
 [ 5 85]
 [ 2 55]
 [ 9 60]
 [ 2 80]
 [ 3 78]] , Normalization X_train : [[ 0.21417647 -1.54296583]
 [-0.59969411 -0.03956323]
 [ 1.84191763  1.32716641]
 [ 1.02804705  1.53217586]
 [-1.41356469 -1.88464824]
 [-0.19275882 -1.20128342]
 [ 0.21417647  0.37045567]
 [ 1.43498234  1.05382049]
 [-1.0066294  -0.5179186 ]
 [ 0.21417647 -0.72292805]
 [ 0.62111176  1.19049345]
 [ 1.02804705  0.09710974]
 [-0.59969411  0.84881104]
 [-0.19275882 -0.17623619]
 [-0.19275882  0.84881104]
 [-1.41356469 -1.20128342]
 [ 1.43498234 -0.85960101]
 [-1.41356469  0.50712863]
 [-1.0066294   0.37045567]]


In [15]:
def Relu(X):
    relu = np.maximum(0,X)
    # print(relu)

    return relu

In [16]:
tmp_activation = Relu(X_norm)

In [17]:
def sigmoid(X):
    err = 1 + np.exp(-X)
    z = 1 / err

    return z

In [18]:
tmp_array = np.array([-2,0,3])
tmp_activation_relu = Relu(tmp_array)
tmp_activation_sigmoid = sigmoid(tmp_array)
print(tmp_activation_sigmoid)
print(tmp_activation_relu)


[0.11920292 0.5        0.95257413]
[0 0 3]


In [19]:
def weights_bias(n_input,n_hidden,n_output):
    rng = np.random.default_rng(42)
    W1 = rng.standard_normal((n_input,n_hidden)) * 0.1
    B1 = np.zeros((1,n_hidden))
    W2 = rng.standard_normal((n_hidden,n_output)) * 0.1
    B2 = np.zeros((1,n_output))
    print(W1.shape)
    return W1,B1,W2,B2


In [20]:
W1,B1,W2,B2 = weights_bias(2,4,1)
print(W1.shape,B1.shape,W2.shape,B2.shape)

(2, 4)
(2, 4) (1, 4) (4, 1) (1, 1)


In [21]:
def forward_pass(X,W1,B1,W2,B2):
    err_relu = np.dot(X,W1) + B1
    hidden_layer = Relu(err_relu)
    err_sigmoid = np.dot(hidden_layer,W2) + B2
    output_layer = sigmoid(err_sigmoid)

    return hidden_layer,output_layer

In [22]:
tmp_hidden,tmp_output = forward_pass(X_norm,W1,B1,W2,B2)
print(tmp_hidden.tolist())
print(tmp_output.tolist())


[[0.307564386062013, 0.17864783627665762, 0.0, 0.0689398343820462], [0.0, 0.06751907674152713, 0.0, 0.0], [0.0, 0.0, 0.15519347764682687, 0.13127361844785654], [0.0, 0.0, 0.09673731166762808, 0.04824055144441867], [0.32462777335288157, 0.39242351309185514, 0.0, 0.0], [0.22850093215702036, 0.17647527641343425, 0.0, 0.019859483697124612], [0.0, 0.0, 0.020808818853723966, 0.008429296916424746], [0.0, 0.0, 0.1211605047776835, 0.10164308337688466], [0.07037402434703514, 0.17213015668698745, 0.0, 0.0], [0.14757212866481023, 0.0718641964679739, 0.006830957385959693, 0.043006746896779864], [0.0, 0.0, 0.06183072245674946, 0.020771106997219027], [0.012379897913257103, 0.0, 0.07839136849118748, 0.09362345454363477], [0.0, 0.0, 0.0, 0.0], [0.028510610410516935, 0.0429957266525796, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.19130089218854596, 0.30343714658461873, 0.0, 0.0], [0.21143754486615177, 0.0, 0.09669924720909603, 0.16215362084250612], [0.0, 0.08097123031652764, 0.0, 0.0], [0.0, 0.05644788022758011

In [23]:
print(tmp_hidden.shape)
print(tmp_output.shape)

(19, 4)
(19, 1)


In [24]:
def binary_cross_entropy(y_true,y_pred):
    eps = 1e-8
    y_pred = np.clip(y_pred,eps,1-eps)
    loss = -((y_true*np.log(y_pred)) + (1-y_true) * np.log(1 - y_pred))
    return np.mean(loss)

In [25]:
print(Y_train.shape)
print(tmp_output.shape)

(19, 1)
(19, 1)


In [26]:
loss = binary_cross_entropy(Y_train,tmp_output)
print(loss)

0.6880830465937814


In [27]:
# backward pass

blame_output = tmp_output - Y_train


print(blame_output.shape)

(19, 1)


In [28]:
dW2 = np.dot(tmp_hidden.T,blame_output) / len(X_norm)
dB2 = np.mean(blame_output , axis=0 , keepdims=True)

In [29]:
print(f"dW2(Shape) : {dW2.shape}")
print(f"dB2(Shape) : {dB2.shape}")


dW2(Shape) : (4, 1)
dB2(Shape) : (1, 1)


In [30]:
blame_hidden_layer = np.dot(blame_output,W2.T)
print(blame_hidden_layer.shape)

(19, 4)


In [31]:
relu_mask = tmp_hidden > 0
blame_hidden_relulayer = blame_hidden_layer * relu_mask

In [32]:
blame_hidden_relulayer.shape

(19, 4)

In [33]:
dW1= np.dot(X_norm.T , blame_hidden_relulayer) / len(X_norm)
dW1.shape

(2, 4)

In [34]:
dB1 = np.mean(blame_hidden_relulayer , axis=0 , keepdims=True)
dW2.shape

(4, 1)

In [35]:
print(f"W1 : {dW1.shape} , B1 : {dB1.shape}, W2 : {dW2.shape}, B2 : {dB2.shape}")

W1 : (2, 4) , B1 : (1, 4), W2 : (4, 1), B2 : (1, 1)


In [36]:
def update_parameters(W1,B1,W2,B2,dW1,dB1,dW2,dB2,alpha):

    W1 = W1 - alpha * dW1
    B1 = B1 - alpha * dB1
    W2 = W2 - alpha * dW2
    B2 = B2 - alpha * dB2

    return W1,B1,W2,B2


In [37]:
print(binary_cross_entropy(Y_train,tmp_output))

0.6880830465937814


In [38]:
alpha = 0.1
W1_new, B1_new, W2_new, B2_new = update_parameters(W1,B1,W2,B2,dW1,dB1,dW2,dB2 , alpha)


In [39]:
new_hidden,new_output= forward_pass(X_norm,W1_new,B1_new,W2_new,B2_new)
print(binary_cross_entropy(Y_train,new_output))

0.6859977740625876


In [40]:
def backward_pass(X,y,W2,tmp_hidden,tmp_output):
    blame_output = tmp_output - y
    dW2 = np.dot(tmp_hidden.T,blame_output) / len(X)
    dB2 = np.mean(blame_output , axis=0 , keepdims=True)
    blame_hidden_layer = np.dot(blame_output,W2.T)
    relu_mask = tmp_hidden > 0
    blame_hidden_relulayer = blame_hidden_layer * relu_mask
    dW1= np.dot(X.T , blame_hidden_relulayer) / len(X)
    dB1 = np.mean(blame_hidden_relulayer , axis=0 , keepdims=True)


    return dW1,dB1,dW2,dB2

In [41]:
dW1, dB1, dW2, dB2 = backward_pass(X_norm,Y_train,W2_new,new_hidden,new_output,)


In [42]:
print(f"dW1: {dW1.shape} , dB1: {dB1.shape} , dW2: {dW2.shape} , dB2 : {dB2.shape}")

dW1: (2, 4) , dB1: (1, 4) , dW2: (4, 1) , dB2 : (1, 1)


In [43]:
def train(X,y,W1,B1, W2, B2, alpha, epochs):
    losses = []

    for epoch in range(epochs):

        hidden, output = forward_pass(X,W1,B1,W2,B2)
        loss = binary_cross_entropy(y , output)
        losses.append(loss)
        dW1,dB1,dW2,dB2 = backward_pass(X,y,W2 , hidden,output)
        W1,B1,W2,B2 = update_parameters( W1,B1,W2,B2,dW1,dB1,dW2,dB2,alpha)

        if epoch % 100 == 0:
            print(f"Epoch {epoch:4d} : loss { loss:.4f}")
    # forward_pass = forward_pass(X,W1,B1,W2,B2)
    # binary_cross_entropy = binary_cross_entropy(y,X)
    # backward_pass = backward_pass(X,y,W2_new,new_hidden,new_output)
    # update_parameters = update_parameters(W1,B1,W2,B2,dW1,dB1,dW2,dB2 , alpha)

    # epochs = 100
    return W1,B1,W2,B2,losses

In [44]:
W1_temp,B1_tmp,W2_tmp,B2_tmp, losses = train(X_norm,Y_train,W1,B1,W2,B2,alpha=0.1, epochs=1000)

Epoch    0 : loss 0.6881
Epoch  100 : loss 0.3372
Epoch  200 : loss 0.1809
Epoch  300 : loss 0.1517
Epoch  400 : loss 0.1385
Epoch  500 : loss 0.1300
Epoch  600 : loss 0.1234
Epoch  700 : loss 0.1178
Epoch  800 : loss 0.1129
Epoch  900 : loss 0.1083


In [45]:
new_students = np.array([
    [2, 45],
    [9, 90],
    [5, 75],
    [6, 55],
    [8, 60],
    [3, 85],
])

In [46]:
X_norm_new = apply_scaler(new_students, mean,std)
X_norm_new

array([[-1.41356469, -1.88464824],
       [ 1.43498234,  1.19049345],
       [-0.19275882,  0.16544622],
       [ 0.21417647, -1.20128342],
       [ 1.02804705, -0.85960101],
       [-1.0066294 ,  0.84881104]])

In [47]:
hidden , output = forward_pass(X_norm_new,W1_temp,B1_tmp,W2_tmp,B2_tmp)
print(hidden.shape)
print(output.shape)

(6, 4)
(6, 1)


In [48]:
output

array([[1.07900018e-07],
       [9.99999748e-01],
       [9.94204811e-01],
       [4.51543411e-03],
       [9.78235095e-01],
       [9.96973040e-01]])

In [49]:
hidden , output = forward_pass(X_test_norm,W1_temp,B1_tmp,W2_tmp,B2_tmp)
print(hidden.shape)
print(output.shape)

(5, 4)
(5, 1)


In [50]:
output


array([[3.73728566e-06],
       [9.70259922e-01],
       [9.14161408e-04],
       [3.11519481e-09],
       [9.98070723e-01]])

In [60]:

predictions = np.where(output >= 0.5,1,0)
print(predictions.shape)

(5, 1)


In [62]:
test_acc = np.mean(predictions == Y_test)
test_acc

np.float64(0.2)